-- Reference PostgreSQL schema. Django migrations remain the source of truth.
CREATE TABLE licenses_license (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key VARCHAR(18) NOT NULL UNIQUE,
    license_type VARCHAR(20) NOT NULL
        CHECK (license_type IN ('PERMANENT', 'EXPIRY_BASED')),
    created_at TIMESTAMPTZ NOT NULL,
    expiry_date TIMESTAMPTZ NULL,
    hardware_id VARCHAR(255) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    violation_count INTEGER NOT NULL DEFAULT 0 CHECK (violation_count >= 0),
    CONSTRAINT license_type_expiry_consistency CHECK (
        (license_type = 'PERMANENT' AND expiry_date IS NULL)
        OR (license_type = 'EXPIRY_BASED' AND expiry_date IS NOT NULL)
    )
);

CREATE TABLE licenses_activationhistory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id BIGINT NULL REFERENCES licenses_license(id) ON DELETE CASCADE,
    license_key VARCHAR(18) NOT NULL,
    requested_hardware_id VARCHAR(255) NOT NULL,
    registered_hardware_id VARCHAR(255) NULL,
    request_ip INET NULL,
    request_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('SUCCESS', 'REJECTED', 'BLOCKED')),
    reason VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE licenses_auditlog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NULL REFERENCES auth_user(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    license_id BIGINT NULL REFERENCES licenses_license(id) ON DELETE SET NULL,
    request_ip INET NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX licenses_license_active_idx ON licenses_license(is_active);
CREATE INDEX licenses_license_blocked_idx ON licenses_license(is_blocked);
CREATE INDEX licenses_license_expiry_idx ON licenses_license(expiry_date);
CREATE INDEX activation_status_time_idx
    ON licenses_activationhistory(status, request_time);
CREATE INDEX activation_license_time_idx
    ON licenses_activationhistory(license_key, request_time);
CREATE INDEX audit_action_idx ON licenses_auditlog(action);
