# Generated by Django 6.0.6 on 2026-06-20 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, max_length=18, unique=True)),
                ('license_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('EXPIRY_BASED', 'Expiry Based')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hardware_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('computer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('violation_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('expiry_date__isnull', True), ('license_type', 'PERMANENT')), models.Q(('expiry_date__isnull', False), ('license_type', 'EXPIRY_BASED')), _connector='OR'), name='license_type_expiry_consistency')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.license')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, max_length=18)),
                ('requested_hardware_id', models.CharField(max_length=255)),
                ('registered_hardware_id', models.CharField(blank=True, max_length=255, null=True)),
                ('computer_name', models.CharField(max_length=255)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_history', to='licenses.license')),
            ],
            options={
                'ordering': ('-request_time',),
                'indexes': [models.Index(fields=['status', 'request_time'], name='licenses_ac_status_0a657c_idx'), models.Index(fields=['license_key', 'request_time'], name='licenses_ac_license_3d04d5_idx')],
            },
        ),
    ]
