# Generated by Django 6.0.6 on 2026-06-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationhistory',
            name='computer_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='computer_name',
        ),
    ]
