# Generated by Django 6.0.6 on 2026-06-20 05:35

import licenses.utils
from django.db import migrations, models


def populate_blank_license_keys(apps, schema_editor):
    License = apps.get_model("licenses", "License")
    ActivationHistory = apps.get_model("licenses", "ActivationHistory")

    for license_obj in License.objects.filter(license_key=""):
        for _ in range(10):
            key = licenses.utils.generate_license_key()
            if not License.objects.filter(license_key=key).exists():
                license_obj.license_key = key
                license_obj.save(update_fields=("license_key",))
                ActivationHistory.objects.filter(
                    license_id=license_obj.pk,
                    license_key="",
                ).update(license_key=key)
                break
        else:
            raise RuntimeError("Unable to repair a blank license key.")


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_remove_activationhistory_computer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(db_index=True, default=licenses.utils.generate_license_key, editable=False, max_length=18, unique=True),
        ),
        migrations.RunPython(
            populate_blank_license_keys,
            migrations.RunPython.noop,
        ),
    ]
